name: almaraa_drivers
description: A almaraa drivers project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  http: ^0.13.4
  provider: ^6.0.2
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  location: ^4.3.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  package_info: ^2.0.2
  qr_flutter: ^4.0.0
  flutter_dropdown_alert: ^1.0.3
  flutter_advanced_drawer: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_native_splash: ^2.0.5

#flutter_native_splash:
#  image: assets/splash/splash.jpg
#  color: "#FFFFFF"
#  android_disable_fullscreen: true
#  ios: false


flutter:
  uses-material-design: true

  assets:
    - assets/language/ar.json
    - assets/language/en.json
    - assets/images/map.png
    - assets/images/user.png
    - assets/images/almaraa_logo.png
    - assets/images/logo.png
    - assets/images/car.png


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: RA7ICONS
      fonts:
        - asset: assets/icons/RA7ICONS.ttf