name: almaraa_drivers
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.6
  location: ^4.2.3
  geolocator: ^7.0.3
  package_info: ^2.0.2
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0

flutter_native_splash:
  image: assets/images/logo.png
  color: "#FFFFFF"
  android_disable_fullscreen: true



flutter:
  uses-material-design: true

  assets:
    - assets/language/ar.json
    - assets/language/en.json
    - assets/images/turki.png
    - assets/images/turki2.png
    - assets/images/logo.png
    - assets/images/meat.png
    - assets/images/meat2.png


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: RA7ICONS
      fonts:
        - asset: assets/icons/RA7ICONS.ttf